### ISSUE TITLE
Jumbotron Header

### ISSUE THREAD

**Issue by AlesciDavide** [Luca-Rubino/proj-html-vuejs#2]
Jumbotron 

![header-jumbo](https://github.com/Luca-Rubino/proj-html-vuejs/assets/19228924/cb366fa8-1f33-4c99-a244-de1080f0abed)

**Comment by AlesciDavide** [comment]
faccio iooo!!

**Comment by AlesciDavide** [comment]
lol

**Comment by Luca-Rubino** [comment]
Si é riaperta

**Comment by AlesciDavide** [comment]
finito

**Comment by AlesciDavide** [comment]
finita prima importazione

**Comment by Luca-Rubino** [comment]
Perfetto
