### ISSUE TITLE
sixth component Main (Article)

### ISSUE THREAD

**Issue by AlesciDavide** [Luca-Rubino/proj-html-vuejs#8]
sixth component Main (Article)

![sixth component Main (Article)](https://github.com/Luca-Rubino/proj-html-vuejs/assets/19228924/ea2e2f04-24c4-466d-9db8-198697a49fc2)

**Comment by Samuele-Chioda** [comment]
faccio io

**Comment by Samuele-Chioda** [comment]
completato
